# Generated by Django 2.2.7 on 2019-11-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixinlogin', '0002_auto_20191114_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dept',
            field=models.CharField(blank=True, max_length=150, verbose_name='部门'),
        ),
    ]
