# Generated by Django 2.2.7 on 2019-11-16 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weixinlogin', '0004_userprofile_u_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='u_name',
        ),
    ]
