# Generated by Django 2.1.7 on 2019-11-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixinlogin', '0005_remove_userprofile_u_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_oa_id',
            field=models.CharField(blank=True, max_length=150, verbose_name='OA用户id'),
        ),
    ]
