# Generated by Django 2.1.7 on 2019-11-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixinlogin', '0006_userprofile_user_oa_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dept_id',
            field=models.CharField(blank=True, max_length=150, verbose_name='部门id'),
        ),
    ]
