# Generated by Django 2.1.7 on 2020-01-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixinlogin', '0007_userprofile_dept_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='openid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='openid'),
        ),
    ]
