# Generated by Django 2.2.1 on 2020-03-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixinlogin', '0009_auto_20200111_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='手机'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tel_no_dept',
            field=models.CharField(blank=True, max_length=100, verbose_name='工作电话'),
        ),
    ]
