# Generated by Django 2.2.1 on 2020-03-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixinlogin', '0010_auto_20200301_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='paixu_id',
            field=models.IntegerField(blank=True, default=1, max_length=11, verbose_name='通讯录排序号'),
            preserve_default=False,
        ),
    ]
