# Generated by Django 2.2.1 on 2020-03-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixinlogin', '0011_userprofile_paixu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='paixu_id',
            field=models.IntegerField(blank=True, verbose_name='通讯录排序号'),
        ),
    ]
