# Generated by Django 2.2.1 on 2020-03-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixinlogin', '0013_auto_20200303_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_mes',
            field=models.CharField(blank=True, max_length=150, verbose_name='是否具有MES模块权限'),
        ),
    ]
