# Generated by Django 2.2.1 on 2020-03-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixinlogin', '0014_userprofile_is_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_mes_id',
            field=models.CharField(blank=True, max_length=150, verbose_name='MES用户id'),
        ),
    ]
