# Generated by Django 2.2.1 on 2020-03-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixinlogin', '0015_userprofile_user_mes_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_mes_dept',
            field=models.CharField(blank=True, max_length=150, verbose_name='MES部门id'),
        ),
    ]
