# Generated by Django 2.2.1 on 2020-03-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixinlogin', '0016_userprofile_user_mes_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_gerengz',
            field=models.CharField(blank=True, max_length=150, verbose_name='是否具有工资查询权限'),
        ),
    ]
