# Generated by Django 2.1.7 on 2019-11-29 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notifys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_name', models.CharField(max_length=200, verbose_name='发布者')),
                ('to_id', models.TextField(verbose_name='发布部门')),
                ('subject', models.CharField(max_length=200, verbose_name='公告标题')),
                ('content', models.TextField(verbose_name='公告内容')),
                ('send_time', models.DateTimeField(verbose_name='发布时间')),
                ('begin_date', models.IntegerField(max_length=10, verbose_name='开始时间戳')),
                ('end_date', models.IntegerField(max_length=10, verbose_name='结束时间戳')),
                ('attachment_name', models.TextField(verbose_name='附件')),
                ('priv_id', models.TextField(verbose_name='发布角色')),
                ('user_name', models.TextField(verbose_name='发布人员')),
                ('type_id', models.CharField(max_length=200, verbose_name='公告类型')),
            ],
            options={
                'verbose_name': '公告记录',
                'verbose_name_plural': '公告记录',
            },
        ),
    ]
