# Generated by Django 2.1.7 on 2019-11-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchsignin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signin',
            name='FormID',
            field=models.CharField(blank=True, max_length=250, verbose_name='活动id'),
        ),
        migrations.AlterField(
            model_name='signin',
            name='FormerID',
            field=models.CharField(blank=True, max_length=250, verbose_name='活动发起人id'),
        ),
        migrations.AlterField(
            model_name='signin',
            name='content',
            field=models.CharField(blank=True, max_length=250, verbose_name='签到内容'),
        ),
        migrations.AlterField(
            model_name='signin',
            name='endTime',
            field=models.CharField(blank=True, max_length=250, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='signin',
            name='startTime',
            field=models.CharField(blank=True, max_length=250, verbose_name='启动时间'),
        ),
        migrations.AlterField(
            model_name='signin',
            name='topic',
            field=models.CharField(blank=True, max_length=250, verbose_name='签到主题'),
        ),
    ]
