# Generated by Django 2.1.7 on 2019-11-27 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('launchsignin', '0003_auto_20191127_1139'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SigninRecord',
        ),
    ]
