# Generated by Django 2.2.7 on 2019-11-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryMenu', '0008_auto_20190519_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='typeName',
            field=models.CharField(max_length=50, verbose_name='星期'),
        ),
    ]
