# Generated by Django 2.2.7 on 2019-11-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryMenu', '0010_auto_20191118_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='xg_num',
            field=models.IntegerField(default=0, verbose_name='限购数量'),
        ),
        migrations.AddField(
            model_name='menu',
            name='xg_status',
            field=models.CharField(choices=[('启用', '启用'), ('停用', '停用')], default='限购', max_length=30, verbose_name='是否限购'),
        ),
    ]
