# Generated by Django 2.2.7 on 2019-11-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryMenu', '0011_auto_20191118_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='xg_status',
            field=models.CharField(choices=[('限购', '限购'), ('不限购', '不限购')], default='限购', max_length=30, verbose_name='是否限购'),
        ),
    ]
