# Generated by Django 2.2.7 on 2019-11-18 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queryMenu', '0013_auto_20191118_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': '预订餐品', 'verbose_name_plural': '预订餐品'},
        ),
    ]
