# Generated by Django 2.1.7 on 2019-11-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryMenu', '0014_auto_20191118_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='xiaoliang',
            field=models.IntegerField(default=0, verbose_name='销量'),
        ),
    ]
