# Generated by Django 2.1.7 on 2019-11-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryMenu', '0017_auto_20191120_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='status',
            field=models.CharField(choices=[('启用', '启用'), ('停用', '停用')], default='符合', max_length=30, verbose_name='是否符合出售'),
        ),
    ]
