# Generated by Django 2.1.7 on 2019-11-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryMenu', '0020_auto_20191120_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='fh_status',
            field=models.CharField(choices=[('符合', '符合'), ('不符合', '不符合')], default='不符合', max_length=30, verbose_name='是否符合出售'),
        ),
    ]
