# Generated by Django 2.1.7 on 2019-11-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryMenu', '0021_auto_20191120_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='sales_fz',
            field=models.IntegerField(default=0, verbose_name='阈值'),
        ),
    ]
