# Generated by Django 2.1.7 on 2019-11-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryMenu', '0022_menu_sales_fz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='sales',
            field=models.IntegerField(default=0, verbose_name='可预订数量'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='status',
            field=models.CharField(choices=[('上架', '上架'), ('下架', '下架')], default='启用', max_length=30, verbose_name='是否上架'),
        ),
    ]
