# Generated by Django 2.1.7 on 2019-11-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryMenu', '0023_auto_20191121_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='status',
            field=models.CharField(choices=[('上架', '上架'), ('下架', '下架')], default='下架', max_length=30, verbose_name='是否上架'),
        ),
    ]
