# Generated by Django 2.1.7 on 2019-11-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SUBJECT', models.CharField(max_length=200, verbose_name='新闻标题')),
                ('CONTENT', models.TextField(verbose_name='新闻内容')),
                ('PROVIDER', models.CharField(max_length=200, verbose_name='发布者')),
                ('NEWS_TIME', models.DateTimeField(verbose_name='发布时间')),
                ('ATTACHMENT_NAME', models.TextField(verbose_name='附件')),
                ('TYPE_ID', models.CharField(max_length=200, verbose_name='新闻类型')),
                ('TO_ID', models.TextField(verbose_name='发布部门')),
                ('PRIV_ID', models.TextField(verbose_name='发布角色')),
                ('USER_ID', models.TextField(verbose_name='发布人员')),
            ],
            options={
                'verbose_name': '新闻记录',
                'verbose_name_plural': '新闻记录',
            },
        ),
    ]
