# Generated by Django 2.2.7 on 2019-11-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=50, verbose_name='种类')),
                ('name', models.CharField(max_length=50, verbose_name='名字')),
                ('src', models.ImageField(default='image/defaultImg.jpg', upload_to='image', verbose_name='图片')),
                ('price', models.FloatField(default=9999.0, verbose_name='售价')),
                ('status', models.CharField(choices=[('启用', '启用'), ('停用', '停用')], default='启用', max_length=30, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '餐品',
                'verbose_name_plural': '餐品',
            },
        ),
    ]
