# Generated by Django 2.2.7 on 2019-11-18 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queryCaidan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': '今日餐品', 'verbose_name_plural': '今日餐品'},
        ),
    ]
