# Generated by Django 2.1.7 on 2020-02-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order_tj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(blank=True, max_length=150, verbose_name='部门')),
                ('number_h1', models.IntegerField(blank=True, default=0, verbose_name='盒饭1数量')),
                ('number_h2', models.IntegerField(blank=True, default=0, verbose_name='盒饭2数量')),
            ],
            options={
                'verbose_name': '当日部门订单统计',
                'verbose_name_plural': '当日部门订单统计',
            },
        ),
    ]
