# Generated by Django 2.1.7 on 2020-02-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_tj', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order_tj',
            options={'verbose_name': '按部门订单统计', 'verbose_name_plural': '按部门订单统计'},
        ),
        migrations.AddField(
            model_name='order_tj',
            name='lq_date_time',
            field=models.DateTimeField(blank=True, default='2020-02-20 18:00:00.000000', verbose_name='领取时间'),
            preserve_default=False,
        ),
    ]
