# Generated by Django 2.2.7 on 2019-11-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Xiaofei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, verbose_name='用户名')),
                ('wacc_sj', models.DateTimeField(verbose_name='消费时间')),
                ('Old_card_cash', models.FloatField(default=0.0, verbose_name='前现金额')),
                ('Old_card_subsidy', models.FloatField(default=0.0, verbose_name='前补贴额')),
                ('New_card_cash', models.FloatField(default=0.0, verbose_name='现现金额')),
                ('New_card_subsidy', models.FloatField(default=0.0, verbose_name='现补贴额')),
                ('Cash_amt', models.FloatField(default=0.0, verbose_name='现金消费')),
                ('Sub_amt', models.FloatField(default=0.0, verbose_name='补贴消费')),
            ],
            options={
                'verbose_name': '消费记录',
                'verbose_name_plural': '消费记录',
            },
        ),
    ]
