# Generated by Django 2.2.7 on 2019-11-17 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queryXiaofei', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xiaofei',
            name='Old_card_cash',
        ),
        migrations.RemoveField(
            model_name='xiaofei',
            name='Old_card_subsidy',
        ),
    ]
