# Generated by Django 2.2.1 on 2020-01-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryXiaofei', '0002_auto_20191117_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xiaofei',
            name='Cash_amt',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='现金消费'),
        ),
        migrations.AlterField(
            model_name='xiaofei',
            name='New_card_cash',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='现现金额'),
        ),
        migrations.AlterField(
            model_name='xiaofei',
            name='New_card_subsidy',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='现补贴额'),
        ),
        migrations.AlterField(
            model_name='xiaofei',
            name='Sub_amt',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='补贴消费'),
        ),
    ]
