# Generated by Django 2.2.1 on 2020-01-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryXiaofei', '0004_auto_20200111_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xiaofei',
            name='Cash_amt',
            field=models.FloatField(default=0.0, verbose_name='现金消费'),
        ),
        migrations.AlterField(
            model_name='xiaofei',
            name='New_card_cash',
            field=models.FloatField(default=0.0, verbose_name='现现金额'),
        ),
        migrations.AlterField(
            model_name='xiaofei',
            name='New_card_subsidy',
            field=models.FloatField(default=0.0, verbose_name='现补贴额'),
        ),
        migrations.AlterField(
            model_name='xiaofei',
            name='Sub_amt',
            field=models.FloatField(default=0.0, verbose_name='补贴消费'),
        ),
    ]
