# Generated by Django 2.2.1 on 2020-03-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querySms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='remind_time',
            field=models.DateTimeField(blank=True, verbose_name='提醒时间'),
        ),
    ]
