# Generated by Django 2.2.1 on 2020-03-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querySms', '0002_auto_20200301_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='remind_time',
            field=models.IntegerField(blank=True, verbose_name='提醒时间'),
        ),
    ]
