# Generated by Django 2.2.7 on 2019-11-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_order_u_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='u_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='用户姓名'),
        ),
    ]
