# Generated by Django 2.2.7 on 2019-11-16 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_order_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='u_name',
        ),
    ]
