# Generated by Django 2.1.7 on 2019-11-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_order_jz_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, max_length=200, verbose_name='评论'),
        ),
    ]
