# Generated by Django 2.1.7 on 2020-01-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_order_lq_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='typeName',
            field=models.CharField(max_length=50, verbose_name='种类'),
        ),
    ]
