# Generated by Django 2.1.7 on 2020-01-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_auto_20200110_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cost',
            field=models.FloatField(blank=True, default=9999.0, verbose_name='订单总价'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_time',
            field=models.DateTimeField(blank=True, verbose_name='下单时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='food_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='名字'),
        ),
        migrations.AlterField(
            model_name='order',
            name='jz_date_time',
            field=models.DateTimeField(blank=True, verbose_name='截止时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='lq_date_time',
            field=models.DateTimeField(blank=True, verbose_name='领取时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.IntegerField(blank=True, default=0, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='score',
            field=models.IntegerField(blank=True, default=5, verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(blank=True, max_length=20, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='order',
            name='typeName',
            field=models.CharField(blank=True, max_length=50, verbose_name='种类'),
        ),
        migrations.AlterField(
            model_name='order',
            name='username',
            field=models.CharField(blank=True, max_length=200, verbose_name='用户名'),
        ),
    ]
