# Generated by Django 2.1.7 on 2020-01-20 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_auto_20200120_1526'),
        ('order', '0024_auto_20200120_1453'),
    ]

    operations = [
    ]
